version: '3.8'
services:
  mysql-test:
    image: mysql:8.0
    container_name: mp06-uf04-api-mysql-test
    environment:
      MYSQL_DATABASE: chatdb_test
      MYSQL_USER: chatuser_test
      MYSQL_PASSWORD: chatpass_test
      MYSQL_ROOT_PASSWORD: root_password_test
    ports:
      - "3308:3306"
    volumes:
      - mysql-test-data:/var/lib/mysql
    restart: always
volumes:
  mysql-test-data:
